/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import POO.clientesPOO;


import IMAGENES.TextPrompt;
import MODELOVENDEDORES.gestion;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author rodri
 */
public class addClient extends javax.swing.JFrame {

    /**
     * Creates new form addCl
     */
    String uaurioTemp;
    public addClient() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Establece textos fantasmas en los text Fiels, lo que hace que
        // el usuario entienda mejor el programa
        TextPrompt tfU = new TextPrompt("Nombre:",nomcli);
        TextPrompt tfc = new TextPrompt("NIT: ",nitcli);
        TextPrompt tfa = new TextPrompt("Correo: ",corcli);
        sexo.add(mas);
        sexo.add(fem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomcli = new javax.swing.JTextField();
        corcli = new javax.swing.JTextField();
        nitcli = new javax.swing.JTextField();
        mas = new javax.swing.JRadioButton();
        fem = new javax.swing.JRadioButton();
        jButton27 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(224, 245, 244));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 36)); // NOI18N
        jLabel1.setText("Crear Cliente");

        nomcli.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        nomcli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomcliKeyTyped(evt);
            }
        });

        corcli.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        corcli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                corcliKeyTyped(evt);
            }
        });

        nitcli.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        nitcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nitcliActionPerformed(evt);
            }
        });
        nitcli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nitcliKeyTyped(evt);
            }
        });

        mas.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        mas.setText("Masculino");
        mas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masMouseClicked(evt);
            }
        });

        fem.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        fem.setText("Femenino");
        fem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                femMouseClicked(evt);
            }
        });

        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/salir.png"))); // NOI18N
        jButton27.setBorder(null);
        jButton27.setBorderPainted(false);
        jButton27.setContentAreaFilled(false);
        jButton27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton27.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/salir.png"))); // NOI18N
        jButton27.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/salir.png"))); // NOI18N
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton27)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(corcli, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nitcli, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomcli, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel1)))
                        .addGap(3, 3, 3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(mas)
                            .addGap(18, 18, 18)
                            .addComponent(fem))
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(nomcli, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nitcli, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corcli, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mas)
                    .addComponent(fem))
                .addGap(36, 36, 36)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton27)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomcliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomcliKeyTyped
        nomcli.setBackground(new Color (255,255,255));
    }//GEN-LAST:event_nomcliKeyTyped

    private void nitcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nitcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nitcliActionPerformed

    private void nitcliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nitcliKeyTyped
        nitcli.setBackground(new Color (255,255,255)); 
    }//GEN-LAST:event_nitcliKeyTyped

    private void corcliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_corcliKeyTyped
        corcli.setBackground(new Color (255,255,255));
    }//GEN-LAST:event_corcliKeyTyped

    private void masMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masMouseClicked
        mas.setForeground(Color.BLACK);
        fem.setForeground(Color.BLACK);
    }//GEN-LAST:event_masMouseClicked

    private void femMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femMouseClicked
        mas.setForeground(Color.BLACK);
        fem.setForeground(Color.BLACK);
    }//GEN-LAST:event_femMouseClicked

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        //Vuelve a la vista vTrabajador
        vTrabajador v = new vTrabajador();
        v.setVisible(true);
        v.label(uaurioTemp, 1);
        dispose();
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Valida que todos los campos tengan texto o hayan sido elegidos 
        //En caso de que no, se pintaran de rojo indicando que hacen falta
        if(nomcli.getText().isEmpty()||nitcli.getText().isEmpty()||corcli.getText().isEmpty()
                ||(mas.isSelected()==false &&fem.isSelected()==false)){
            
            JOptionPane.showMessageDialog(null, "DEBE LLENAR Y/O SELECCIONAR TODOS LOS CAMPOS");
                Color ca = new Color(255,160,160);
            if(nomcli.getText().isEmpty()){
                nomcli.setBackground(ca);
            }
            if(nitcli.getText().isEmpty()){
                nitcli.setBackground(ca);
            }
            if(corcli.getText().isEmpty()){
                corcli.setBackground(ca);
            }
            if(mas.isSelected()==false && fem.isSelected() == false){
                mas.setForeground(Color.red);
                fem.setForeground(Color.red);
            }
        }else{
            enviarDatosven();
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * Recibe de la vista vTrabajador el nombre del TRABAJADOR que accedio 
     * para no perderlo
     * Lo guarda temporalmente para reenviarlo a vTrabajador al cambiar de vista
     * @param usuario 
     */
    public void recibir(String usuario){
        this.uaurioTemp = usuario;
    }
    
    /**
     * Crea un nuevo cliente en base a los datos ingresados en la vista 
     * luego de crearlo, se evian datos a la vista vTrabajador, desactivan esta
     * vista y habilitan vTrabajador
     */
    public void enviarDatosven(){
        if(mas.isSelected()==true){
            clientesPOO ah = new clientesPOO(nomcli.getText(),Integer.parseInt(nitcli.getText()),corcli.getText(),"M");
            gestion ad = new gestion();
            ad.crearClientes(ah);
            vTrabajador vp = new vTrabajador();
            vp.label(uaurioTemp, 1);
            vp.setVisible(true);
            dispose();
        }else if(fem.isSelected()==true){
            clientesPOO ah = new clientesPOO(nomcli.getText(),Integer.parseInt(nitcli.getText()),corcli.getText(),"F");
            gestion ad = new gestion();
            ad.crearClientes(ah);
            vTrabajador vp = new vTrabajador();
            vp.label(uaurioTemp, 1);
            vp.setVisible(true);
            dispose();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField corcli;
    private javax.swing.JRadioButton fem;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton27;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mas;
    private javax.swing.JTextField nitcli;
    private javax.swing.JTextField nomcli;
    private javax.swing.ButtonGroup sexo;
    // End of variables declaration//GEN-END:variables
}
