/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import MODELO.ProductoImplementacion;
import MODELOVENDEDORES.crearPDF;
import MODELOVENDEDORES.gestion;
import POO.clientesPOO;
import POO.facturaPOO;
import POO.hisventasPOO;
import POO.listarFacturasPOO;
import POO.productosPOO;
import com.itextpdf.text.DocumentException;
import IMAGENES.TextPrompt;
import MODELO.EnProcesoDAO;
import MODELO.EnProcesoImplementacion;
import MODELO.productoDAO;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.LinkedList;
import java.util.Collections;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.time.LocalDateTime;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author rodri
 */
public class vTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form vendedores
     */
    int caja;
    String vendedo;
    //Listas principalmente en el guardado de datos de las facturas     
    LinkedList<String> a = new LinkedList<>();
    LinkedList<String> b = new LinkedList<>();
    LinkedList<String> c = new LinkedList<>();
    LinkedList<String> d = new LinkedList<>();    
    LinkedList<String> cP = new LinkedList<>();
    LinkedList<String> canti = new LinkedList<>();
    //Modelos para las tablas a utilizar
    DefaultTableModel t1,t2,t3,tEnProceso;
    //Obtiene la fecha actual
    LocalDate fechaActual = LocalDate.now();
    
    public vTrabajador() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        tabla();
        jPanel5.setVisible(false);
        suma();
        fecha.setText(fechaActual.toString());
        jButton6.setBackground(new Color(149,240,150));
        noFaca();
        bienvenidoVendedor.setText("");
        limp.setBackground(new Color(136,143,255));
        datosEnProceso();
        btnFinalizar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bienvenidoVendedor = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lim = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        factu = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        nomU = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        niU = new javax.swing.JTextField();
        feU = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        correoF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nitF = new javax.swing.JTextField();
        generoF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboCliente = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        nombreF = new javax.swing.JTextField();
        limp = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        noFac = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        codpro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        canpro = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaEnProceso = new javax.swing.JTable();
        btnFinalizar = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(168, 189, 217));

        bienvenidoVendedor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTabbedPane1.setBackground(new java.awt.Color(0, 204, 204));

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado Ventas"));

        lim.setText("Limpiar");
        lim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limActionPerformed(evt);
            }
        });

        jLabel16.setText("Filtrar por:");

        jLabel17.setText("No.Factura:");

        jLabel18.setText("Nombre:");

        jLabel19.setText("NIT:");

        jLabel20.setText("Fecha:");

        jButton8.setText("Aplicar Filtro");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel21.setText("Fliltrados:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lim)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel16)))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(factu)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(nomU)
                                        .addGap(68, 68, 68)))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(feU)
                                    .addComponent(niU))))
                        .addGap(87, 87, 87))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lim)
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(factu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(niU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(nomU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(feU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(50, 50, 50)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Ventas", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("SELECCIONAR CLIENTE"));

        jLabel2.setText("Filtrar por:");

        jLabel3.setText("Filtrados:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Correo:");

        jLabel6.setText("Nit:");

        jLabel7.setText("Género:");

        jLabel8.setText("Cliente:");

        comboCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClienteActionPerformed(evt);
            }
        });

        jButton4.setText("Nuevo Cliente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Aplicar Filtro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        limp.setText("Limpiar");
        limp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(limp))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboCliente, 0, 214, Short.MAX_VALUE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(correoF, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(nombreF))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generoF, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(nitF))))
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(nitF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(correoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(generoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(limp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(comboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(15, 15, 15))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("AGREGAR PRODUCTOS"));

        jLabel9.setText("Fecha:");

        fecha.setText("jLabel10");

        jLabel11.setText("No.");

        noFac.setText("jLabel12");

        jLabel13.setText("Codigo:");

        jLabel14.setText("Cantidad:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton6.setText("Vender");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel15.setText("Total:");

        canpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canproActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(codpro, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addGap(80, 80, 80)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(fecha)
                                .addGap(109, 109, 109)
                                .addComponent(jLabel11)
                                .addGap(31, 31, 31)
                                .addComponent(noFac))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(canpro, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addGap(31, 31, 31)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel15)
                        .addGap(28, 28, 28)
                        .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fecha)
                    .addComponent(jLabel11)
                    .addComponent(noFac))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(canpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Nueva Venta", jPanel4);

        tablaEnProceso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaEnProceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEnProcesoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaEnProceso);

        btnFinalizar.setText("Trabajo Finalizado");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(btnFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(233, 233, 233))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(btnFinalizar)
                .addGap(0, 105, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("En el Taller", jPanel7);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/salir.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/salir.png"))); // NOI18N
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/salir.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bienvenidoVendedor)
                .addGap(122, 122, 122)
                .addComponent(jButton9)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9)
                    .addComponent(bienvenidoVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //Regresa al login
        Login lg = new Login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       /*
        Ejecuta el metodo obtner datos para poder ver los clientes en la lista 
        si el cliente no existe, da el mensaje de que no existe
        */
        datosObtener();
       if(a.contains(nombreF.getText())==false){
           JOptionPane.showMessageDialog(null, "Cliente no encontrado");
       }
       noFaca();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClienteActionPerformed
        llenarCasillas();
    }//GEN-LAST:event_comboClienteActionPerformed

    private void limpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpActionPerformed
        vaciar();
    }//GEN-LAST:event_limpActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Abre la ventana para crear un nuevo cliente
        addClient ac = new addClient();
        ac.setVisible(true);
        //Envia a la nueva vista los datos del vendedor, que no debem ser perdidos
        ac.recibir(vendedo);
        dispose();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //Comienza a crear factura
        try {
            jalarDato();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(vTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(vTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(vTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpiartabla();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Busca el articulo que coincida con el codigo ingresado
        int a = Integer.parseInt(codpro.getText());
        int b = Integer.parseInt(canpro.getText());
        gestion ra = new gestion();
        productoDAO da = ra.obtenerPro(a);
        if(!da.getStrnombreProducto().isEmpty()||!da.getStrnombreProducto().equals("")){
            datostabla(a,b);
            suma();
        }else{
            JOptionPane.showMessageDialog(null, "Articulo no encontrado");
       }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        tablageneral();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void limActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limActionPerformed
        nomU.setText("");
        niU.setText("");
        feU.setText("");
        factu.setText("");
        noFaca();
    }//GEN-LAST:event_limActionPerformed

    private void canproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canproActionPerformed

    private void tablaEnProcesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEnProcesoMouseClicked
        btnFinalizar.setVisible(true);
    }//GEN-LAST:event_tablaEnProcesoMouseClicked

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        finalizar();
    }//GEN-LAST:event_btnFinalizarActionPerformed
    
    /**
     * Obtiene la informacion necesaria del Trabajador de los datos ingresados
     * en el login
     * @param usuario
     * @param a 
     */
    public void label(String usuario, int a) {
        vendedo = usuario;
        bienvenidoVendedor.setText("");
        bienvenidoVendedor.setText("Bienvenido "+usuario);
        caja = a;
    }
    
    /**
     * Lista los datos de los vehiculos que estan en el taller, para que los 
     * trabajadores puedan verla 
     */
    private void datosEnProceso() {
        String columnas[] = {"ID", "Descripcion del Trabajo","Mecanico a Cargo","Dueño","Tipo de Vehiculo"};
        tEnProceso = new DefaultTableModel(null, columnas);
        EnProcesoImplementacion im = new EnProcesoImplementacion();
        for(EnProcesoDAO dat: im.listar()){
            Object ayuda[] = new Object[5];
            ayuda[0] = dat.getIntID();
            ayuda[1] = dat.getStrDescripcionProceso();
            ayuda[2] = dat.getStrNombreMecanico();
            ayuda[3] = dat.getStrNombreDueno();
            ayuda[4] = dat.getStrVehiculo();
            tEnProceso.addRow(ayuda);
        }
        //Pone el filtro en los encabezados de la tabla
        tablaEnProceso.setModel(tEnProceso);
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tEnProceso);
        tablaEnProceso.setRowSorter(sorter);
          
    }
    
    /**
     * Metodo que se ejecuta para realizar un filtro en base a la informacion 
     * ingresada por el usuario
     * 
     * Los datos que coinciden con lo que el usuario ingreso, se guardan en un 
     * Combobox para usarlos posteriormente
     */
    private void datosObtener(){
        LinkedList<String> ca = new LinkedList<>();
        comboCliente.removeAllItems();
        a.clear(); b.clear(); c.clear(); d.clear(); ca.clear();
        String nombrev = nombreF.getText();
        String correov = correoF.getText();
        String nitv = nitF.getText();
        String generov = generoF.getText();
        gestion ev = new gestion();
        for (clientesPOO dat : ev.listarClientes(nombrev, nitv, correov, generov)) {   
            Object ayuda[] = new Object[4];
            ayuda[0] = dat.getNombre();
            ayuda[1] = dat.getNit();
            ayuda[2] = dat.getCorreo();
            ayuda[3] = dat.getGenero();
            
            ca.add(String.valueOf(ayuda[0]));
            Collections.sort(ca);  
            a.add(String.valueOf(ayuda[0]));
            b.add(String.valueOf(ayuda[1]));
            c.add(String.valueOf(ayuda[2]));
            d.add(String.valueOf(ayuda[3]));
        }
        for (String clientes: ca){
            comboCliente.addItem(clientes);
        }
    }
    /**
     * Si se encuentra el cliente que se estaba buscando en el ComboBox
     * al darle click este muestra todos los datos del cliente en los text fields
     * designados, asi como tambien habilita la vista de ingreso de productos a la
     * factura
     */
    private void llenarCasillas(){
        nombreF.setText("");
        correoF.setText("");
        nitF.setText("");
        generoF.setText("");
        String nombre = String.valueOf(comboCliente.getSelectedItem());
        if(a.contains(nombre)){
            
            int az = a.indexOf(nombre);
            
            nombreF.setText(a.get(az));
            correoF.setText(c.get(az));
            nitF.setText(b.get(az));
            generoF.setText(d.get(az));
            jPanel5.setVisible(true);
        }else{
            jPanel5.setVisible(false);
        }
    }
    /**
     * Vacia todos los campos de la pestaña Nueva venta
     */
    private void vaciar(){
        nombreF.setText("");
        correoF.setText("");
        nitF.setText("");
        generoF.setText("");
        if(nombreF.getText().isEmpty()&&nitF.getText().isEmpty()&&correoF.getText().isEmpty()&&generoF.getText().isEmpty()){
            comboCliente.removeAllItems();
        }
    }
    
    /**
     * Establece los encabezados de las columnas 
     */
    public void tabla(){
       String columnas[] = {"Codigo", "Nombre", "Cantidad", "Precio", "Subtotal"};
        t1 = new DefaultTableModel(null, columnas);
        jTable1.setModel(t1);
    }
    
    /**
     * Luego de tomar el codigo del producto y la cantidad estos se envian para 
     * buscar el producto y hacer el respectivo calculo
     * Posteriormente se muestran los datos en la tabla
     * @param cod
     * @param can 
     */
    public void datostabla(int cod,int can) {
        
        gestion ad = new gestion();
        for (productoDAO dat : ad.listarProducto(cod)) {
            Object ayuda[] = new Object[6];
            ayuda[0] = dat.getIntID();
            ayuda[1] = dat.getStrnombreProducto();
            ayuda[2] = can;
            ayuda[3] = dat.getDblPrecioProducto();
            ayuda[4] = dat.getDblPrecioProducto()* can;
            
            if(dat.getIntStock()<=0){
                JOptionPane.showMessageDialog(null, "Producto agotado");
                
                break;
            }else if((dat.getIntStock())<can){
                JOptionPane.showMessageDialog(null, "Articulo insuficiente. Cantidad en existencia: "+dat.getIntStock());
                break;
            }
            t1.addRow(new Object[]{
                ayuda[0],ayuda[1],ayuda[2],ayuda[3],ayuda[4]
            });
            ad.modificarProducto(cod, can);
        }
        jTable1.setModel(t1);
        
        codpro.setText("");
        canpro.setText("");
    }
    
    /**
     * Suma toda la columna de subtotales y lo muestra en el text field designado
     * @return float
     */
    private float suma(){
       
        int c = jTable1.getRowCount();
        float suma = 0;
        for (int i = 0; i < c; i++) {
            suma += Float.parseFloat(jTable1.getValueAt(i, 4).toString());
        }
        
        total.setText(String.valueOf(suma));
        return suma;
    }

    /**
     * Toma todos los datos que necesita para la creacion de la factura
     * Lanza excepciones en caso de que algo salga mal 
     * @throws FileNotFoundException
     * @throws DocumentException
     * @throws IOException 
     */
    private void jalarDato() throws FileNotFoundException, DocumentException, IOException{
        LocalDateTime datetime = LocalDateTime.now();
        int cajaV = caja;
        String noFactura = noFac.getText();
        String hora = String.valueOf(datetime);
        String nomVendedor = vendedo;
        String nit = nitF.getText();
        String nombreCliente = nombreF.getText();
        String fechaV = fecha.getText();
        //datos de la compra
        String ttl = total.getText();
        facturaPOO fp = new facturaPOO(cajaV,noFactura,nit,nombreCliente,fechaV,ttl);
        crearPDF cp = new crearPDF();
        LinkedList<facturaPOO> factura = new LinkedList<>();
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            String idProducto = String.valueOf(jTable1.getValueAt(i, 0));
            String nombreProducto = String.valueOf(jTable1.getValueAt(i, 1));
            String cantidad = String.valueOf(jTable1.getValueAt(i, 2));
            String precio = String.valueOf(jTable1.getValueAt(i, 3));
            String subtotal = String.valueOf(jTable1.getValueAt(i, 4));
            //enviar linkedlist por parametros
            factura.add(new facturaPOO(idProducto,nombreProducto,cantidad,precio,subtotal));
        }
        
        String a = factura+"\n"+noFactura+"\n"+fechaV+"\n"+hora+"\n"+nomVendedor+"\n"+cajaV+"\n"+nit+"\n"+nombreCliente+"\n"+ttl;
        cp.crearDocumento(factura,noFactura, fechaV,hora, nomVendedor, String.valueOf(cajaV),nit,nombreCliente,ttl);
        crearFactura(a);
    }
    
    /**
     * Envia las instrucciones para guardar la factura en la DB
     * @param a 
     */
    public void crearFactura(String a){
        crearPDF cpa = new crearPDF();
        gestion ra = new gestion();
        clientesPOO cp = ra.mostrarCliente(nitF.getText());
        if(cp != null){
            int asd = cp.getId();
            hisventasPOO hv = new hisventasPOO(asd,fecha.getText(),total.getText(),a);
        
            ra.crearhisVentas(hv);
        }else{
            System.out.println("ERROR en crear factura");
        }
        
        
    }
    
    /**
     * Limpia la tabla de las ventas
     */
    private void limpiartabla(){
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            //t1.removeRow(0);
            t1.removeRow(i);
        }
        total.setText("");
        
    }
    
    /**
     * Establece el numero de factura que toca
     * asi como tambien lista los datos de la factura
     */
    private void noFaca(){
        
        String columnas[] = {"No Factura", "Nit", "Nombre", "Fecha", "Total","Accion"};
        t2 = new DefaultTableModel(null, columnas);
        gestion ra = new gestion();
       for (listarFacturasPOO dat : ra.listarFacturas()) {
            Object ayuda[] = new Object[6];
            ayuda[0] = dat.getNo_factura();
            ayuda[1] = dat.getNit();
            ayuda[2] = dat.getNombreC();
            ayuda[3] = dat.getFecha();
            ayuda[4] = dat.getTotal();
            ayuda[5] = "ACCION";    
            
            
            noFac.setText(String.valueOf(dat.getNo_factura()+1));
            
            t2.addRow(ayuda);
        }
       jTable2.setModel(t2);
       jTable2.setRowHeight(32);
    }
    
    /**
     * lista los datos de la factura
     */
    private void tablageneral(){
        
        String columnas[] = {"No Factura", "Nit", "Nombre", "Fecha", "Total","Accion"};
        t3 = new DefaultTableModel(null, columnas);
        gestion ra = new gestion();
       for (listarFacturasPOO dat : ra.listarfacturasU(factu.getText(), niU.getText(), nomU.getText(), feU.getText())) {
            Object ayuda[] = new Object[6];
            ayuda[0] = dat.getNo_factura();
            ayuda[1] = dat.getNit();
            ayuda[2] = dat.getNombreC();
            ayuda[3] = dat.getFecha();
            ayuda[4] = dat.getTotal();
            ayuda[5] = dat.getAccion();    
            
            
            //noFac.setText(String.valueOf(dat.getNo_factura()+1));
            
            t3.addRow(ayuda);
        }
       jTable2.setModel(t3);
       jTable2.setRowHeight(32);
    }
    
    
    /**
     * Permite a un trabajador eliminar un trabajo mecanico 
     * Borrandolo de la base de datos
     */
    private void finalizar(){
        int id = (int)tablaEnProceso.getValueAt(tablaEnProceso.getSelectedRow(), 0);
        EnProcesoImplementacion en = new EnProcesoImplementacion();
        en.eliminar(id);
        tEnProceso.fireTableDataChanged();
        datosEnProceso();
        tablaEnProceso.repaint();
        JOptionPane.showMessageDialog(null, "Trabajo Finalizado");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenidoVendedor;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JTextField canpro;
    private javax.swing.JTextField codpro;
    private javax.swing.JComboBox<String> comboCliente;
    private javax.swing.JTextField correoF;
    private javax.swing.JTextField factu;
    private javax.swing.JTextField feU;
    private javax.swing.JLabel fecha;
    private javax.swing.JTextField generoF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton lim;
    private javax.swing.JButton limp;
    private javax.swing.JTextField niU;
    private javax.swing.JTextField nitF;
    private javax.swing.JLabel noFac;
    private javax.swing.JTextField nomU;
    private javax.swing.JTextField nombreF;
    private javax.swing.JTable tablaEnProceso;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
